name: Run ScheduleDisconnectLight

concurrency:
  group: state-updater1
  cancel-in-progress: false
  
on:
  workflow_dispatch: {}         # ручной запуск
 #  schedule:
 #   - cron: '*/5 * * * *'       # каждые 5 минут по UTC
  repository_dispatch:
     types: [run-from-crone]
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  ZVONOK_KEY: ${{ secrets.ZVONOK_KEY }}
jobs:
  run:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with latest main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main



      - name: Create GCP key file
        shell: pwsh
        run: |
          $keyPath = Join-Path $env:GITHUB_WORKSPACE "gcp-key.json"
          '${{ secrets.GCP_SA_KEY }}' | Out-File -FilePath $keyPath -Encoding utf8 -NoNewline
          "Wrote key to: $keyPath"
          # (опционально) проверка что это JSON
          Get-Content $keyPath | Select-Object -First 1
          
      - name: Run EXE
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ZVONOK_KEY: ${{ secrets.ZVONOK_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}\gcp-key.json
          CHAT_ID:  ${{ secrets.CHAT_ID }}
        run: |
          cd ScheduleDisconnectLight\bin\Debug
          .\ScheduleDisconnectLight.exe

      - name: Commit updated appState.json
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Добавляем appState.json и коммитим, если есть изменения
          git add appState.json
          git commit -m "Update appState.json" || echo "No changes to commit"

          # Подтягиваем последние изменения, не ломаясь из-за локальных правок
          git pull --rebase --autostash origin main || echo "Pull failed"

          # Пушим обратно в main
          git push origin HEAD:main || echo "Push failed"
     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
