name: Run ScheduleDisconnectLight

on:
  workflow_dispatch: {}     # ручний запуск
  schedule:
    - cron: '*/5 * * * *'   # кожні 5 хвилин по UTC

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run EXE
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
        run: |
          cd ScheduleDisconnectLight\bin\Debug
          .\ScheduleDisconnectLight.exe
