name: Run ScheduleDisconnectLight

on:
  workflow_dispatch:   # дает кнопку "Run workflow" в Actions

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore ScheduleDisconnectLight.sln

      - name: Build project
        run: msbuild ScheduleDisconnectLight\ScheduleDisconnectLight.csproj /p:Configuration=Debug

      - name: Run EXE
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
        run: |
          cd ScheduleDisconnectLight\bin\Debug
          ScheduleDisconnectLight.exe
